spring.application.name=email-notification-consumer

#Deve ser diferente do
server.port = 8082

#kafka
spring.kafka.bootstrap-servers=localhost:9092

# Se dois consumers [ Quem recebe a mensagem ] diferentes (tipo o de email e o de SMS, no futuro) usarem group-id
# diferentes, cada grupo recebe sua prÃ³pria cÃ³pia completa das mensagens
spring.kafka.consumer.group-id=email-notification-group

# Controla o que acontece quando esse consumer nunca leu nada daquele tÃ³pico antes (primeira vez rodando).
# earliest = lÃª todas as mensagens jÃ¡ publicadas no tÃ³pico, desde o inÃ­cio
spring.kafka.consumer.auto-offset-reset=earliest

# Resilience4j - Retry
resilience4j.retry.instances.emailService.max-attempts=4
resilience4j.retry.instances.emailService.wait-duration=1s
resilience4j.retry.instances.emailService.enable-exponential-backoff=true
resilience4j.retry.instances.emailService.exponential-backoff-multiplier=2

# Resilience4j - Circuit Breaker
# o circuit breaker olha pras as ultimas 10 chamadas feitas, pra decidir a taxa de falha. Ha uma "janela deslizante" Sempre
# olhando as 10 mais recentes, nao o historico inteiro desde o inicio da aplicaÃ§Ã£o
resilience4j.circuitbreaker.instances.emailService.sliding-window-size=10

# Se, dentro dessa janela de 10 chamadas, 50% ou mais falharem, o circuito abre
resilience4j.circuitbreaker.instances.emailService.failure-rate-threshold=50

# Depois de abrir, o circuito fica bloqueando todas as chamadas por 10 segundos, sem nem tentar de verdade
resilience4j.circuitbreaker.instances.emailService.wait-duration-in-open-state=10s

# Depois desses 10 segundos, o circuito entra num estado intermediario chamado "half-open" (meio-aberto): ele deixa
# passar sao 3 chamadas de teste, pra ver se o servico ja¡ voltou a funcionar
resilience4j.circuitbreaker.instances.emailService.permitted-number-of-calls-in-half-open-state=3

# Sem isso, o circuito ficaria aberto pra sempre atÃ© alguÃ©m manualmente resetar
resilience4j.circuitbreaker.instances.emailService.automatic-transition-from-open-to-half-open-enabled=true

# por seguranca, o Actuator nao expoe tudo por padrao (so /health basico). Aqui liberamos explicitamente os 3 endpoints
# que vamos usar:
# health (aplicacao esta viva?),
# metrics (metricas em formato Spring),
# prometheus (metricas no formato especifico do Prometheus)
management.endpoints.web.exposure.include=health,metrics,prometheus

# faz o /actuator/health mostrar detalhes (tipo "Postgres conectado? Kafka conectado?"), nao so um "UP"/"DOWN" generico
management.endpoint.health.show-details=always