spring.application.name=email-notification-consumer

#Deve ser diferente do
server.port = 8082

#kafka
spring.kafka.bootstrap-servers=localhost:9092

# Se dois consumers [ Quem recebe a mensagem ] diferentes (tipo o de email e o de SMS, no futuro) usarem group-id
# diferentes, cada grupo recebe sua própria cópia completa das mensagens
spring.kafka.consumer.group-id=email-notification-group

# Controla o que acontece quando esse consumer nunca leu nada daquele tópico antes (primeira vez rodando).
# earliest = lê todas as mensagens já publicadas no tópico, desde o início
spring.kafka.consumer.auto-offset-reset=earliest
